### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by ForgedChemist** [PurpleHP/Intertech-Wolf-Of-BIST#7]
- [ ] **95 push hakkımız kaldı yarın için**
- [x] ilerlemeniz kısmının fiziğini yazma (kolaysa)
- [x] AI stringify
- [x] yapılan kursların isminin yanına tick gelmesi
- [x] quizlerin eklenmesi
- [x] Register'dan sonraki quiz'de yapılan performans bazlı belirli getEducationByUserId'lerin status'unu done'a çekme (mesela orta seviye döndürüyorsa hard code ile temel seviye eduId'leri Done a çeksin)
- [x] Register'dan sonraki quiz'de for loop ile her eduId için new statuslu getEducationByUserId açma
- [x] progressBar'ın çalışan halini ilerlemeniz bölümüne ekleme
- [x] Progress bar duzgun calistirma
- [x] user cikisi yapma mekanigi
- [x] navbar da eğer giriş yapılmışsa giriş yap silinicek isim gelecek
- [x] home a konulucak progressBar da veri çekilirken user yoksa "your progress" invis yapma
- [x] score counter düzeltme
- [x] "your progress" yada "all courses" gibi ingilizce yazıları türkçeye çekme
- [x] Login ekraninda hatali giris yapinca uyari vermesi lazim (basarli ya da basarisiz girislerde home page atiyor)
- [x] #8
